# Generated by Django 2.0.13 on 2019-03-18 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=100)),
                ('course_description', models.TextField(blank=True, null=True)),
                ('course_price', models.FloatField(default=29.99)),
                ('price_currency', models.CharField(choices=[('Dolar', '$'), ('Euro', '€'), ('Türk Lirası', 'TL')], max_length=5)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('course_status', models.IntegerField(choices=[('Show', 1), ('Hide', 2)], max_length=3)),
                ('course_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
