# Generated by Django 2.0.13 on 2019-03-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_status',
            field=models.IntegerField(choices=[('Show', 1), ('Hide', 2)]),
        ),
    ]
