# Generated by Django 2.0.13 on 2019-03-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_auto_20190319_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='university_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
