# Generated by Django 2.0.13 on 2019-03-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_auto_20190319_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
