# Generated by Django 2.0.13 on 2019-04-06 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_teacher_teacher_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.University'),
        ),
    ]
