# Generated by Django 2.0.13 on 2019-04-06 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_auto_20190406_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.University'),
        ),
    ]
