# Generated by Django 2.0.13 on 2019-04-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_auto_20190406_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='count_subscriber',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Mixed'), (3, 'Hard')], default=None),
        ),
        migrations.AddField(
            model_name='course',
            name='popularity',
            field=models.IntegerField(choices=[(1, 'Half Star'), (2, 'One Star'), (3, 'One and Half Star'), (4, 'Two Star'), (5, 'Two and Half Star'), (6, 'Three Star'), (7, 'Three and Half Star'), (8, 'Four Star'), (9, 'Four and Half Star'), (10, 'Five Star')], default=None),
        ),
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.IntegerField(choices=[(1, 'COURSE'), (2, 'SPECIALIZATION'), (3, 'DEGREE COURSE')], default=None),
        ),
    ]
