# Generated by Django 2.0.13 on 2019-04-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0011_auto_20190412_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Mixed', 'Mixed'), ('Hard', 'Hard')], default='Beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='popularity',
            field=models.IntegerField(choices=[(1, 'Half Star'), (2, 'One Star'), (3, 'One and Half Star'), (4, 'Two Star'), (5, 'Two and Half Star'), (6, 'Three Star'), (7, 'Three and Half Star'), (8, 'Four Star'), (9, 'Four and Half Star'), (10, 'Five Star')], default=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='price_currency',
            field=models.CharField(choices=[('$', 'Dolar'), ('€', 'Euro'), ('TL', 'Türk Lirası')], default='TL', max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.CharField(choices=[('Course', 'Course'), ('Specialization', 'Specialization'), ('Certificated Course', 'Certificated Course')], default='Course', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='popularity',
            field=models.IntegerField(choices=[(1, 'Half Star'), (2, 'One Star'), (3, 'One and Half Star'), (4, 'Two Star'), (5, 'Two and Half Star'), (6, 'Three Star'), (7, 'Three and Half Star'), (8, 'Four Star'), (9, 'Four and Half Star'), (10, 'Five Star')], default=10),
        ),
        migrations.AlterField(
            model_name='university',
            name='popularity',
            field=models.IntegerField(choices=[(1, 'Half Star'), (2, 'One Star'), (3, 'One and Half Star'), (4, 'Two Star'), (5, 'Two and Half Star'), (6, 'Three Star'), (7, 'Three and Half Star'), (8, 'Four Star'), (9, 'Four and Half Star'), (10, 'Five Star')], default=10),
        ),
    ]
