version: "3"


services:
  app:
    build:
      context: .
    ports: 
      - "8000:8000"
    volumes:
      - ./univer:/univer
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
  elasticsearch:
    image: elasticsearch:2.4.0
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
    
